apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://services-db:5432/common_database"
  PAYMENT_SERVICE_PORT: "8080"
  PAYMENT_SERVICE_DEBUG_PORT: "5000"
  SERVICES_DB_NAME: "common_database"
  SERVICES_DB_EXTERNAL_PORT: "5432"
  SERVICES_DB_INTERNAL_PORT: "5432"
  SPRING_DATASOURCE_USERNAME: "user"
  SPRING_DATASOURCE_PASSWORD: "password"
  SPRING_DATASOURCE_SCHEMA: "payment_schema"
  KAFKA_BOOTSTRAP_SERVER: "kafka-stateful-set-0.kafka-svc:9092"