apiVersion: v1
kind: Service
metadata:
  name: services-db
spec:
  clusterIP: None        # важно для StatefulSet Headless Service
  selector:
    app: postgresql
  ports:
    - port: 5432
      name: postgres
